# Generated by Django 6.0.2 on 2026-02-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_asset_publisher", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publishedasset",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="publishedasset",
            name="loading",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name="publishedasset",
            unique_together={("page", "asset_type", "loading")},
        ),
    ]
