# Generated by Django 6.0.2 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_asset_publisher", "0002_publishedasset_loading"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publishedasset",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="publishedasset",
            name="position",
            field=models.CharField(blank=True, default="body", max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name="publishedasset",
            unique_together={("page", "asset_type", "loading", "position")},
        ),
    ]
